version = 0.1

[default.global.parameters]
stack_name = "aws-lab-autopilot-dev"
region = "us-east-1"
profile = "weichaol-testenv2-awswhatsnewtest"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
no_fail_on_empty_changeset = true
